# Generated by Django 2.0.6 on 2018-06-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='В большом блоке на главной'),
        ),
    ]
