# Generated by Django 2.0.6 on 2019-04-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_meta_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-born'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
