# Generated by Django 2.0.6 on 2018-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_like_list',
            field=models.CharField(blank=True, max_length=300, verbose_name='id лайкнувших пользователей'),
        ),
    ]
