# Generated by Django 2.0.6 on 2018-06-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_user_like_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='author',
            name='like',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_like_list',
        ),
    ]
