# Generated by Django 2.0.6 on 2018-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_auto_20180611_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='user_list',
            field=models.ManyToManyField(to='forecasts.UserID', verbose_name='Список пользователей, которые оценили прогноз'),
        ),
    ]
