# Generated by Django 2.0.6 on 2018-06-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_auto_20180611_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='user_list',
            new_name='user_id',
        ),
    ]
