# Generated by Django 2.0.6 on 2018-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_auto_20180611_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='forecasts.UserID', verbose_name='Список пользователей, которые оценили прогноз'),
        ),
    ]
