# Generated by Django 2.0.6 on 2018-06-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_auto_20180611_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='come_true',
            field=models.BooleanField(default=False, verbose_name='Сбылось или нет'),
        ),
    ]
