# Generated by Django 2.0.6 on 2018-06-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180614_2351'),
        ('forecasts', '0006_forecast_come_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Игра'),
        ),
    ]
