# Generated by Django 2.0.6 on 2018-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_forecast_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='coefficient',
            field=models.CharField(default='тотал меньше 2.5, коэфф. 1.65', max_length=300, verbose_name='Коэффициент'),
        ),
    ]
