# Generated by Django 2.0.6 on 2018-06-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasts', '0006_forecast_come_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_a', models.CharField(max_length=300, verbose_name='Команда А')),
                ('command_b', models.CharField(max_length=300, verbose_name='Команда Б')),
                ('score', models.CharField(max_length=10, verbose_name='Счет')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.Forecast', verbose_name='Прогноз')),
            ],
        ),
    ]
