# Generated by Django 2.0.6 on 2018-06-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, max_length=10, verbose_name='Счет'),
        ),
    ]
