# Generated by Django 2.0.6 on 2018-06-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubhistory',
            name='meta_title',
        ),
    ]
