# Generated by Django 2.0.6 on 2019-04-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_remove_clubhistory_meta_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubhistory',
            options={'ordering': ['born'], 'verbose_name': 'История клубов', 'verbose_name_plural': 'Истории клубов'},
        ),
    ]
